# Dascalu Laurentiu, 335CA; Tema4 Cell Image Quilting

#   Target
PROGRAMS_spu          := spu
LIBRARY_embed          := lib_spu.a

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
