package ISchedulerCORBA;


/**
* ISchedulerCORBA/ISchedulerServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

abstract public class ISchedulerServerHelper
{
  private static String  _id = "IDL:ISchedulerCORBA/ISchedulerServer:1.0";

  public static void insert (org.omg.CORBA.Any a, ISchedulerCORBA.ISchedulerServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ISchedulerCORBA.ISchedulerServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ISchedulerCORBA.ISchedulerServerHelper.id (), "ISchedulerServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ISchedulerCORBA.ISchedulerServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ISchedulerServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ISchedulerCORBA.ISchedulerServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ISchedulerCORBA.ISchedulerServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ISchedulerCORBA.ISchedulerServer)
      return (ISchedulerCORBA.ISchedulerServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ISchedulerCORBA._ISchedulerServerStub stub = new ISchedulerCORBA._ISchedulerServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ISchedulerCORBA.ISchedulerServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ISchedulerCORBA.ISchedulerServer)
      return (ISchedulerCORBA.ISchedulerServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ISchedulerCORBA._ISchedulerServerStub stub = new ISchedulerCORBA._ISchedulerServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
