package ISchedulerCORBA;


/**
* ISchedulerCORBA/IScheduler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public interface IScheduler extends ISchedulerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IScheduler
