package ISchedulerCORBA;


/**
* ISchedulerCORBA/ISchedulerServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public abstract class ISchedulerServerPOA extends org.omg.PortableServer.Servant
 implements ISchedulerCORBA.ISchedulerServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCPU", new java.lang.Integer (0));
    _methods.put ("getMem", new java.lang.Integer (1));
    _methods.put ("executeJob", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ISchedulerCORBA/ISchedulerServer/getCPU
       {
         String $result = null;
         $result = this.getCPU ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ISchedulerCORBA/ISchedulerServer/getMem
       {
         String $result = null;
         $result = this.getMem ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ISchedulerCORBA/ISchedulerServer/executeJob
       {
         ISchedulerCORBA.SJob job = ISchedulerCORBA.SJobHelper.read (in);
         ISchedulerCORBA.SJobResult $result = null;
         $result = this.executeJob (job);
         out = $rh.createReply();
         ISchedulerCORBA.SJobResultHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ISchedulerCORBA/ISchedulerServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ISchedulerServer _this() 
  {
    return ISchedulerServerHelper.narrow(
    super._this_object());
  }

  public ISchedulerServer _this(org.omg.CORBA.ORB orb) 
  {
    return ISchedulerServerHelper.narrow(
    super._this_object(orb));
  }


} // class ISchedulerServerPOA
