package ISchedulerCORBA;


/**
* ISchedulerCORBA/ISchedulerServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public interface ISchedulerServerOperations 
{
  String getCPU ();
  String getMem ();
  ISchedulerCORBA.SJobResult executeJob (ISchedulerCORBA.SJob job);
} // interface ISchedulerServerOperations
