package ISchedulerCORBA;


/**
* ISchedulerCORBA/ISchedulerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public abstract class ISchedulerPOA extends org.omg.PortableServer.Servant
 implements ISchedulerCORBA.ISchedulerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("submitJob", new java.lang.Integer (0));
    _methods.put ("getServerID", new java.lang.Integer (1));
    _methods.put ("getResult", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ISchedulerCORBA/IScheduler/submitJob
       {
         ISchedulerCORBA.SJob job = ISchedulerCORBA.SJobHelper.read (in);
         short $result = (short)0;
         $result = this.submitJob (job);
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 1:  // ISchedulerCORBA/IScheduler/getServerID
       {
         short $result = (short)0;
         $result = this.getServerID ();
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 2:  // ISchedulerCORBA/IScheduler/getResult
       {
         short jobID = in.read_short ();
         ISchedulerCORBA.SJobResult $result = null;
         $result = this.getResult (jobID);
         out = $rh.createReply();
         ISchedulerCORBA.SJobResultHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ISchedulerCORBA/IScheduler:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IScheduler _this() 
  {
    return ISchedulerHelper.narrow(
    super._this_object());
  }

  public IScheduler _this(org.omg.CORBA.ORB orb) 
  {
    return ISchedulerHelper.narrow(
    super._this_object(orb));
  }


} // class ISchedulerPOA
