package ISchedulerCORBA;

/**
* ISchedulerCORBA/ISchedulerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public final class ISchedulerHolder implements org.omg.CORBA.portable.Streamable
{
  public ISchedulerCORBA.IScheduler value = null;

  public ISchedulerHolder ()
  {
  }

  public ISchedulerHolder (ISchedulerCORBA.IScheduler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ISchedulerCORBA.ISchedulerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ISchedulerCORBA.ISchedulerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ISchedulerCORBA.ISchedulerHelper.type ();
  }

}
