package ISchedulerCORBA;


/**
* ISchedulerCORBA/SJobResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public final class SJobResult implements org.omg.CORBA.portable.IDLEntity
{
  public String m_result = null;

  public SJobResult ()
  {
  } // ctor

  public SJobResult (String _m_result)
  {
    m_result = _m_result;
  } // ctor

} // class SJobResult
