package ISchedulerCORBA;


/**
* ISchedulerCORBA/SJobResultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

abstract public class SJobResultHelper
{
  private static String  _id = "IDL:ISchedulerCORBA/SJobResult:1.0";

  public static void insert (org.omg.CORBA.Any a, ISchedulerCORBA.SJobResult that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ISchedulerCORBA.SJobResult extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_result",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ISchedulerCORBA.SJobResultHelper.id (), "SJobResult", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ISchedulerCORBA.SJobResult read (org.omg.CORBA.portable.InputStream istream)
  {
    ISchedulerCORBA.SJobResult value = new ISchedulerCORBA.SJobResult ();
    value.m_result = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ISchedulerCORBA.SJobResult value)
  {
    ostream.write_string (value.m_result);
  }

}
