package ISchedulerCORBA;

/**
* ISchedulerCORBA/SJobResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public final class SJobResultHolder implements org.omg.CORBA.portable.Streamable
{
  public ISchedulerCORBA.SJobResult value = null;

  public SJobResultHolder ()
  {
  }

  public SJobResultHolder (ISchedulerCORBA.SJobResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ISchedulerCORBA.SJobResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ISchedulerCORBA.SJobResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ISchedulerCORBA.SJobResultHelper.type ();
  }

}
