package ISchedulerCORBA;


/**
* ISchedulerCORBA/SJob.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public final class SJob implements org.omg.CORBA.portable.IDLEntity
{
  public String m_job = null;

  public SJob ()
  {
  } // ctor

  public SJob (String _m_job)
  {
    m_job = _m_job;
  } // ctor

} // class SJob
