package ISchedulerCORBA;

/**
* ISchedulerCORBA/SJobHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IScheduler.idl
* Monday, December 28, 2009 7:50:06 PM EET
*/

public final class SJobHolder implements org.omg.CORBA.portable.Streamable
{
  public ISchedulerCORBA.SJob value = null;

  public SJobHolder ()
  {
  }

  public SJobHolder (ISchedulerCORBA.SJob initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ISchedulerCORBA.SJobHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ISchedulerCORBA.SJobHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ISchedulerCORBA.SJobHelper.type ();
  }

}
